// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error(
    '❌ Missing Supabase environment variables!\n' +
    'Please create a .env file with the following variables:\n' +
    'VITE_SUPABASE_URL=your_supabase_url\n' +
    'VITE_SUPABASE_PUBLISHABLE_KEY=your_supabase_anon_key'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const isConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

// Create client with fallback so the app loads; auth/data calls fail until .env is set (see .env.example).
export const supabase = createClient<Database>(
  isConfigured ? SUPABASE_URL! : 'https://placeholder.supabase.co',
  isConfigured ? SUPABASE_PUBLISHABLE_KEY! : 'placeholder-key',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    }
  }
);